# This rule is not used by the project vm-inventory-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the virtualization.sre.org.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vm-inventory-operator
    app.kubernetes.io/managed-by: kustomize
  name: inventoryconfig-editor-role
rules:
- apiGroups:
  - virtualization.sre.org.io
  resources:
  - inventoryconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtualization.sre.org.io
  resources:
  - inventoryconfigs/status
  verbs:
  - get
