apiVersion: virtualization.sre.org.io/v1alpha1
kind: InventoryConfig
metadata:
  labels:
    app.kubernetes.io/name: vm-inventory-operator
    app.kubernetes.io/managed-by: kustomize
  name: inventoryconfig-sample
spec:
  # TODO(user): Add fields here
